### ISSUE TITLE
audio drop outs every 5 minutes

### ISSUE THREAD

**Issue by JohanDegraeve** [SpikeApp/Spike#1]
If it's every 5 minutes, then that's probably due to the phone muted check. This check is done very 5 minutes, although it was originally not aligned with a reading, but maybe in your version it is.

It plays a sound also, irrespective if mute check alert is on or off.

It's probably better to do the mutecheck only if the alert is on for the time.

And maybe the method to play that sound also needs to be changed. It's different than playing an alert sound
ANE, mutechecker.m, playmutesound

**Comment by miguelkennedy** [comment]
I haven't aligned it with the readings... But normally the AlarmService does kick in when a new reading comes and the mutechecker fires... do you think we can play the mutechecker sound file inside the ane using the same audiosessions that we use in the spoken readings?

**Comment by JohanDegraeve** [comment]
I think yes, would need to be tried

**Comment by JohanDegraeve** [comment]
ok done

**Comment by miguelkennedy** [comment]
Done? You changed the ane and are testing it now?

**Comment by JohanDegraeve** [comment]
No not yet

Op di 20 feb. 2018 om 14:01 schreef RooTShell <notifications@github.com>

**Comment by miguelkennedy** [comment]
OK!

**Comment by miguelkennedy** [comment]
Can we close this?

**Comment by JohanDegraeve** [comment]
yes

**Comment by miguelkennedy** [comment]
Done!
