### ISSUE TITLE
Sensor stopped if no calibration after app restart

### ISSUE THREAD

**Issue by JohanDegraeve** [SpikeApp/Spike#10]
- start app
- start sensor but don't calibrate yet
- close app 
- restart app

Looks as if sensor status is back to not started

Note that this is also on iosxdripreader, I'm logging it in order not to forget

**Comment by miguelkennedy** [comment]
Yes, I noticed this when coding Spike... iOSxDrip does the same... Sometime ago I actually came across the code that resets the sensor status when calibrations < 2 but now I don't remember where I saw that code :D

**Comment by miguelkennedy** [comment]
Maybe this is the root cause? https://github.com/SpikeApp/Spike/blob/master/src/model/ModelLocator.as#L154

**Comment by JohanDegraeve** [comment]
Oh god, i don't remember why I did that.
This can be removed, in any case after a restart calibration restarts completely because the first calibration is stored in memory, not in database, until the second calibration is done.



By the way loggings in database are also not used anymore.

**Comment by miguelkennedy** [comment]
Yeah, if it can be removed than do it... I+ll let you do it, I don't want to mess anything ;)

**Comment by JohanDegraeve** [comment]
solved in commit f63819abbeb5bcb46527d3ada0170c12feecd5ec
