### ISSUE TITLE
Feature Request: Basal Insulin Displayed on Chart

### ISSUE THREAD

**Issue by sooperlooper** [SpikeApp/Spike#117]
![screen shot 2018-08-07 at 3 05 00 pm](https://user-images.githubusercontent.com/36587731/43805080-4ca3a4e8-9a53-11e8-90f3-c81f7f6adbff.png)

This feature would help Spikers understand how their basal insulin is affecting their BG and allow them to make adjustments accordingly. It's especially useful for pumpers as fine tuning basal rates is a major component of insulin pump therapy.

In addition, basal rates for DIY Loopers are automatically adjusted every 5 mins. Knowing what our basal rate is every 5 mins is just as important as knowing what our BG reading is every 5 mins. Having it graphically displayed like it is in Nightscout helps us determine if the algorithm has been working correctly (ie. setting the appropriate basal rate for our current glucose level) and if we need to adjust certain settings.  

Basal rate changes could be read directly from the Loop app or from Nightscout. 

Thank you so much for your consideration of this important feature!

**Comment by analogmonster** [comment]
Agree I would like this, miss it from nightscout

**Comment by daktau** [comment]
I concur, this would be an extremely useful feature to introduce.

**Comment by sooperlooper** [comment]
@miguelkennedy I was just wondering if this feature is still on the todo list?

**Comment by sooperlooper** [comment]
🎉🎊💯 I can't even imagine how complex this must be. It will definitely take Spike to the next level. Thank you so much for improving all of our lives.
