### ISSUE TITLE
First alarm overwrites mute

### ISSUE THREAD

**Issue by JohanDegraeve** [SpikeApp/Spike#12]
Reported by Lukas on facebook
First planed loud high or low alarm, in my case from 23:00 on, always overwrites mute status. Once snoozed, all the alarms that follow respect the mute state of the phone…Can be very annoying, at the cinema or at a diner or something…anybody else?

**Comment by JohanDegraeve** [comment]
Seems difficult to reproduce, I think I had it once when I first tried (on iosxdrip but should be the same) - after that I was not able to reproduce.

Anyone who can describe the steps to reproduce ?

**Comment by JohanDegraeve** [comment]
I think I have a solution
testing

**Comment by miguelkennedy** [comment]
Ok... haven't tested it yet if I can reproduce this bug... Let me know if you need me to test it.

**Comment by JohanDegraeve** [comment]
I'm testing a change on iosxdripreader, I will first test a few days and probably do a TestFlight release, then port to Spike
