### ISSUE TITLE
Feature Request: remove "Fullscreen Display" when fullscreen view is enabled

### ISSUE THREAD

**Issue by rob-scheepens** [SpikeApp/Spike#120]
On iPad, when I select "FullScreen", the bar at the top showing "Fullscreen Display" should disappear after an x amount of seconds, in order to minimize the amount of text on screen (similar to how Safari's address bar disappears when enabling fullscreen view).

**Comment by miguelkennedy** [comment]
We're not planning to implement this because it would take a considerable amount of coding and hacking due to limitations of the UI Framework Spike is built on, it doesn't support it...
