### ISSUE TITLE
Error in translation of plural hours in Snooze popups

### ISSUE THREAD

**Issue by uthne** [SpikeApp/Spike#131]
There is an issue with translation of plural of "hours" in the Snoozer and Pre-snoozer popups. It uses the translated word for "hour" and adds a plural "s". This turns out wrong in translations, at least in Scandinavian languages.

There is already a plural hours translation in the alarmservice.properties, but it could be an issue where it replaces "hour" with a translation before it replaces "hours".

**Comment by m-a-v** [comment]
I've provided a bugfix for this issue.

**Comment by m-a-v** [comment]
@miguelkennedy I need your help to test and merge it. Could you please contact me.

**Comment by m-a-v** [comment]
This has been fixed with the latest release.
