### ISSUE TITLE
Watch Calendar 

### ISSUE THREAD

**Issue by anapaulalago** [SpikeApp/Spike#132]
Whenever there is an update the previously selected calendar for glucose recording (Apple Watch integration) is lost.

**Comment by miguelkennedy** [comment]
This is actually done by designs. In older version of Spike the user could keep a calendar history. This feature was removed because it created issues for a lot of users.

**Comment by JohnKitching** [comment]
I think the help in the app is out of date (in watch settings). It says history is saved in the calendar.
