### ISSUE TITLE
ISF (Insulin Sensitivity Factor)

### ISSUE THREAD

**Issue by Sperolaw** [SpikeApp/Spike#139]
I need to set my ISF for different values during the day but the ISF ranges from 1.2 to 1.8, I am currently using 1.5 all day but I wish I could change in 0.1 increments during the day. Set at 1 is too low and 2 is too high. I guess I am rather insulin resistant!

**Comment by miguelkennedy** [comment]
I will add this in the next update (0.2 increments)

**Comment by Sperolaw** [comment]
Fantastic, much appreciated. Just made a donation as well.

 

Lawrence Spero

921 Bertha Avn.,

Gabriola. BC V0R 1X3

250 247-0261

Photos:  <http://spero.smugmug.com/> http://spero.smugmug.com
