### ISSUE TITLE
When editing "meal" treatment via the "+" cannot set insulin or carbs to zero

### ISSUE THREAD

**Issue by bobhavlin** [SpikeApp/Spike#141]
The dialog that pops up to edit a treatment does not allow to set to zero via the "-": insulin only goes down to 0.1 and carbs to 1.0.  This happens even if the treatment was entered with a zero value in either field.

**Comment by miguelkennedy** [comment]
Why would you want to go to less than 0.1U and 1g of carbs?

**Comment by bobhavlin** [comment]
This happens when a “meal” is entered with a time delay.  If you edit either entry it changes the zero to nonzero.

**Comment by miguelkennedy** [comment]
Thank you for clarifying.... Just fixed it. Download the 3.5.2 update due to be released this Wednesday ;)
