### ISSUE TITLE
Feature Request: Support for FDDB

### ISSUE THREAD

**Issue by thbonk** [SpikeApp/Spike#142]
It would be cool, if you could also support FDDB database. 
API documentation is available here: https://fddb.info/api/v17/documentation/
The API allows to pass a language key, hence it would be possible to display the food names in the language that is set in Spike.

**Comment by miguelkennedy** [comment]
Hi.

Integration to fddb is not planned since you can already use the OpenFoodFacts database (more than 700.000 foods) in Spike and search them in your native language.

Happy holidays.
