### ISSUE TITLE
Setting up Spike followers for iOS?

### ISSUE THREAD

**Issue by pclafferty** [SpikeApp/Spike#144]
I see the thread explaining how to set up Spike followers for NS, but is there similar functionality (and instruction) for iPhone users?

**Comment by miguelkennedy** [comment]
I don't get your question. Spike is for iPhone only and to be able to work in follower mode will always require fetching data from a NS site.

Tutorial available here: https://github.com/SpikeApp/Spike/wiki/Spike-Follower-Mode
