### ISSUE TITLE
enable Spike to send iOS12 Critical Alerts

### ISSUE THREAD

**Issue by mieslep** [SpikeApp/Spike#146]
iOS12 has rethought how notifications work, and there is now a way to allow Do Not Disturb "exceptions" using Critical Alerts, and CGM is definitely one of the use cases.

https://www.apple.com/ie/ios/ios-12/features/

"A new type of opt-in alert for important information, like reports from a healthcare provider, which you’ll receive even during Do Not Disturb"

https://developer.apple.com/documentation/usernotifications/unnotificationsettings/2963116-criticalalertsetting

Not entirely sure if/how iOS dev process works to get the entitlement to use this, but it certainly seems a handy feature.

**Comment by miguelkennedy** [comment]
Hi,

This requires especial approval by Apple in order to get the entitlement. Because Spike is not o the App Store, we can't make a request for it.
