### ISSUE TITLE
Food database help

### ISSUE THREAD

**Issue by analogmonster** [SpikeApp/Spike#147]
Hi. I am creating custom foods. What is the link box for?

**Comment by miguelkennedy** [comment]
It's there in case you want to add a link to a webpage about that food. If you add a link, after you add that food and select it you'll have a button in the food details that allows you to visit that link (webpage). It's completely optional though....

**Comment by analogmonster** [comment]
Thanks for the help. I didnt see this anywhere in the Wiki when looking under food manager
