### ISSUE TITLE
Calibration 

### ISSUE THREAD

**Issue by nathangiovannini3** [SpikeApp/Spike#15]
When you press the calibration button does not always exit the screen that allows you to insert the calibration spike version 1.1.2

**Comment by miguelkennedy** [comment]
Hi Nathan, I don't think I understand exactly what the problem is... When you press the calibration button it's not supposed to exit any screen, just show a popup...

**Comment by miguelkennedy** [comment]
Oh, wait... I think I got it, if you press cancel then the calibration doesn't reappear... I was able to reproduce it... will fix it as soon as possible.

**Comment by miguelkennedy** [comment]
Fixed! Patch will be available in the next update... Thanks for reporting it! ;)
