### ISSUE TITLE
Apply a Temporary Basal

### ISSUE THREAD

**Issue by daktau** [SpikeApp/Spike#155]
Is it possible in the Spike App to apply a temporary basal?

I have opened the treatments panel from the + button but I cannot see how it is done if it is.

Displaying the current basal insulin as Night Scout does is definitely a feature that I would appreciate.

Great Coding, many thanks!!

**Comment by thbonk** [comment]
I didn't find a menu item for that either, I guess that it's not available. I realy woudl like to have that feature, since I apply temporary basal rates very frequently.

**Comment by daktau** [comment]
Basal feature now implemented. Fantastic work, thank you.
