### ISSUE TITLE
Treatment under Follower mode 

### ISSUE THREAD

**Issue by ArthurCamara** [SpikeApp/Spike#161]
What is the justification for not having the treatment option when in follower mode for G6? I couldn't find this anywhere.

**Comment by ArthurCamara** [comment]
I'm sorry if I wasnt specific. I'm using the dexcom share follower mode, not the nightscout. 
Yes, I've entered the password, and I can see my readings ok. But the treatment option is not present in the main menu.

**Comment by ArthurCamara** [comment]
I do realize that this is by design, (according to https://github.com/SpikeApp/Spike/wiki/Dexcom-Share-Follower-Mod) but I was just curious on the reasoning behind it.

**Comment by m-a-v** [comment]
Always look at the Changelog. The explanation is written there:
https://github.com/SpikeApp/Spike/wiki/Changelog
https://github.com/SpikeApp/Spike/wiki/Dexcom-Share-Follower-Mode
