### ISSUE TITLE
Calibration only uses the last entered BG value for Freestyle Libre CGMs

### ISSUE THREAD

**Issue by davidcoffin** [SpikeApp/Spike#166]
If I’ve read the code correctly, for Freestyle Libre CGMs Spike almost always only uses the last calibration BG value entered to calibrate. And since it is only using one data point, it cannot fit both a slope and an intercept, so the slope is fixed. 

This is not what I expected calibration to do. I expected calibration to do some form of robust linear regression using all the calibration data I entered, which is exactly what is done for Dexcom CGMs. 

I’ll walk through the code below.

calculateWLS is called whenever a calibration BG is entered to set the slope and intercept on a Calibration object. Initial values for the slope and intercept are computed using a closed form weighted linear regression predicting calibration BG values from CGM raw values. (The code for this is in [Calibration.as#L542](https://github.com/SpikeApp/Spike/blob/a3d578257f1cd081bd324d6b57641331572fa639/src/database/Calibration.as#L542) to [Calibration.as#L566](https://github.com/SpikeApp/Spike/blob/a3d578257f1cd081bd324d6b57641331572fa639/src/database/Calibration.as#L566).)

If the slope is out of bounds the slope is set to the output of slopeOOBHandler. The bounds for the slopes are set in the DexParameters and LiParameters classes. LiParameters is used whenever isTypeLimiter returns true, i.e. for all Freestyle Libre CGMs.

LiParameters sets both the upper and lower bounds to 1, so for Freestyle Libre CGMs, unless the initial value for the slope computed by linear regression is precisely 1, slopeOOBHandler will be called. It is extremely unlikely that the slope computed by linear regression will be precisely 1, especially as more calibrations are entered. 

Once the calibrations slope has been updated to the output of slopeOOBHandler (e.g. to 1) the calibration intercept is set to (bg-raw)*slope. This only uses the BG value from the last entered calibration. (The code for this is on lines [Calibration.as#L592](https://github.com/SpikeApp/Spike/blob/a3d578257f1cd081bd324d6b57641331572fa639/src/database/Calibration.as#L592) and [Calibration.as#L600](https://github.com/SpikeApp/Spike/blob/a3d578257f1cd081bd324d6b57641331572fa639/src/database/Calibration.as#L600).) 

I hope that’s clear! 

It looks like both XDrip and XDripPlus use LiParametersNonFixed by default now (code [here](https://github.com/jamorham/xDrip-plus/blob/03b8aa1bfebdca3787eab3eddff8083a1a663fa7/app/src/main/res/xml/pref_advanced_settings.xml#L704)). These are the LiParameter values commented out in the current codebase. Switching to these would fix this issue.

**Comment by JohanDegraeve** [comment]
It's good to see someone has taken the time to analyse the code and understands the calibration algorithm.
I only ported the code from xdripplus without understanding what it does, that's almost two years ago now - this change in LiParameters, that's indeed not yet in Spike.

I assume we should test this first with some users to see of the results are better ?
I'm not compiling Spike, Miguel is doing that.
I could do the change in iosxdripreader if you want, then I would need your device UDID.

**Comment by davidcoffin** [comment]
I'd be very happy to test it. Would I be able to run iosxdripreader and Spike at the same time?

**Comment by JohanDegraeve** [comment]
Yes you can , see stackoverflow : https://stackoverflow.com/questions/37331502/can-multiple-ios-apps-on-the-same-device-connect-to-the-same-peripheral

Follow these steps
- open Spike, scan, wait till connected
- close Spike
- open iosxcripreader, scan, wait till connected
- open Spike
- as of now, for both apps didUpdateValueForCharacteristic will be called when the transmitter sends data.
(tested with just 2 readings, seems to work)

**Comment by davidcoffin** [comment]
Hi Johan,

We've used iosxdripreader and Spike concurrently for 3 weeks (the last week of one sensor, and the whole two week life of a second sensor), and iosxdripreader with the calibration patch does seem to be more accurate. 

However the behaviour is quite different, in particular currently when you enter a calibration is Spike while the CGM readings are level the next adjusted CGM values displayed in Spike match the calibration value. While this is not be statistically sound (because the finger prick values aren't perfectly accurate either) it feels quite intuitive and people would definitely notice it if it changed. 

For that reason I think switching to LiParametersNonFixed should be a config option and turned off by default.

**Comment by JohanDG** [comment]
Hi David,

ok that's interesting info.
We will have to wait for Miguel to have this released. 

@miguelkennedy the changes i did in iosxdripreader are here : https://github.com/JohanDegraeve/iosxdripreader/commit/764fca4f7f28fd4b6c363d3022b029611fcdbd85

**Comment by miguelkennedy** [comment]
Thank you... will take a look at it soon...

**Comment by robertbliss** [comment]
Hi all, I'm a little concerned that in the light of the above, the calibration advice I've previously posted in the FB group may be incorrect for Spiker's using Libre - my post is here https://www.facebook.com/groups/spikeapp/permalink/2260323374288394/ Bearing in mind this is going to be referred to in the new Loop Integration instructions for Spike, should I revise the calibration advice, as I was under the impression every calibration is used, where as the above implies only the last one is used.

**Comment by davidcoffin** [comment]
Hi @robertbliss,

I've just read through your post. Based on my understanding of the current calibration code in Spike, I would say your advice is valid for Dexcom CGMs but not for Freestyle Libres.

I use Spike and a Libre for my daughter. We definitely follow most of your advice, but we only recalibrate at the low end of her the range. 

I'll explain why with an example. Lets say we have a Libre that's high at the low end of her range and low at the high end of her range, in other words it's slope is < 1. For the sake of the example lets say the Libre says 4 mmol/L when she's really 3.5 mmol/L and 8 mmol/L when she's really 9 mmol/L. 

So if we calibrated at the high end Spike would use an intercept of +1 and the fixed slope of 1. And that would mean when the Libre says 4 mmol/L and she's really 3.5 mmol/L Spike would report 5 mmol/L, which would lead to missed hypos. So for safeties sake before this gets fixed I'd always prefer to calibrate at the low end of her range even if it Spike is less accurate when she's high.

**Comment by miguelkennedy** [comment]
The whole assumption that Spike uses a different calibration mechanism for Libre or Dexcom is wrong. It uses the same.

Also, the assumption that Spike uses only one calibration data point (the last one) is wrong as well. Spike uses multiple calibration data points https://github.com/SpikeApp/Spike/blob/master/src/database/Calibration.as

When Spike gets a reading from the sensor it attaches the last calibration to the reading object for internal management but that doesn't mean that only the last calibration is used to calculate the bg reading's final glucose value. When you create a calibration Spike looks at previous calibration objects and adjusts the new one based on the old ones.

If a sensor is high in the low end and low in the high end (doesn't matter if it's a Libre or Dexcom), you should calibrate Spike in the low end AND in the high end as well. The extra data points at different ranges will make it more accurate.

**Comment by miguelkennedy** [comment]
EDIT: Actually, scratch that. You are correct regarding the LiParameters issue... I will see if I will implement the changes Johan made and add them as a setting in Spike instead of a default value.

**Comment by miguelkennedy** [comment]
Just finished adding the non-fixed libre parameters to Spike... I already had done that before but frgot to merge my local branch, hence the confusion.

This will be available in the next Spike update that's about to drop very very soon.
