### ISSUE TITLE
Tresiba DIA cannot be configured in treatments 

### ISSUE THREAD

**Issue by udayshah33** [SpikeApp/Spike#171]
I use Tresiba for long acting but cannot configure since the current DIA setting only goes to 8 hours max for long acting.

**Comment by miguelkennedy** [comment]
Make sure you install the new 3.6.1 version or above that has support for basals.

Before you couldn't add Tresiba to Spike because it only supported rapid insulins.

**Comment by udayshah33** [comment]
Thanks Miguel - now if you make Eversense available that would be awesome
