### ISSUE TITLE
mmol delta should be rounded to one decimal

### ISSUE THREAD

**Issue by dabear** [SpikeApp/Spike#18]
13:50 Glucose is 6.7 mmol
13:55 Glucose is 6.9 mmol, delta is reported as 0.17
Delta for mmol users should be rounded to the nearest decimal.

![img_0081](https://user-images.githubusercontent.com/442324/37343227-2b0d7b74-26c7-11e8-921c-6266713f36bd.PNG)

![img_0082](https://user-images.githubusercontent.com/442324/37343253-387cf3f2-26c7-11e8-91cc-9ab0d0f4b3f9.PNG)

**Comment by miguelkennedy** [comment]
Hi, DaBear! Is this happening in Follower or Master mode?

**Comment by dabear** [comment]
Follower

**Comment by hummelstrand** [comment]
I don't agree, I'd rather have better resolution with double decimal digits
 for the delta values.
-- 
     Jonas Hummelstrand
     <http://SuperFly.tv>
     +46-733-970000

**Comment by miguelkennedy** [comment]
I will round it for Follower because Nightscout does round values as well so Spike is fetching rounded values... I will leave it intact for Master... Thanks for reporting this dabear...

**Comment by miguelkennedy** [comment]
Fixed! Available with the next update.... Untouched for master mode because users seem to prefer having more granularity...
