### ISSUE TITLE
Spike update killed it

### ISSUE THREAD

**Issue by Heathmorley** [SpikeApp/Spike#184]
Hi,

Had to go to github and download spike app. unfortunately it will only do one reading then quit. I have to log out and go back in then re connect miao miao then log out then log back in and it only does one measure. I wanted it so that I could have it live on my watch with reading live updated. 

Anybody have a fix?? Help please.

**Comment by m-a-v** [comment]
With version 3.6.2 there are problems for a lot of people. An alternative is being worked on.
