### ISSUE TITLE
Database losing data

### ISSUE THREAD

**Issue by daktau** [SpikeApp/Spike#185]
Just checked my mountain range and there’s loads of dots missing. 
Previously they were there. 
Changed to new platform over 24 hrs ago and all fine. 
Readings stay gone from 90%+ to 16.3%

Any explanation would be greatly appreciated. 

Many thanks,
George

**Comment by daktau** [comment]
NightScout displays all data?

**Comment by marcosArruda** [comment]
Yes, Nightscout is displaying all data. Same problema here, v2.6.2

**Comment by m-a-v** [comment]
With version 3.6.2 there are problems with a lot of people. An alternative is being worked on.
