### ISSUE TITLE
HealthKit not working with the ignition app

### ISSUE THREAD

**Issue by eohland** [SpikeApp/Spike#189]
Hello,
Since I installed the ignition app, I’m unable to sync Spike with HealthKit. I tried to disable/enable HealthKit in the Settings > Share menu and it didn’t prompt for HealthKit permissions.
I also tried to delete the app and reinstall it without restoring the database and it doesn’t ask for the permissions either.

**Comment by GrantGam** [comment]
I also have this issue.

**Comment by m-a-v** [comment]
Several features needed to be removed due to technical limitations of the Ignition platform.
