### ISSUE TITLE
Apple watch authorize

### ISSUE THREAD

**Issue by Jezze83** [SpikeApp/Spike#19]
I have latest ios version on iphone 6, apple watch 1st model with new update. I cant see authorize button at spike when i try to setup spike to apple watch. Watch is connected to iphone.
![0d14031b-69bf-4d33-a3ee-a9327243241c](https://user-images.githubusercontent.com/10639795/37412790-4a60e8a2-27ae-11e8-9e67-94b319ed6105.png)

**Comment by miguelkennedy** [comment]
Hi, Spike already seems to be authorised to access your calendars on your phone... that's why you are able to select the "Spike" calendar from within Spike... So, there's no need to authorise Spike again...
