### ISSUE TITLE
Overlap in scala

### ISSUE THREAD

**Issue by m-a-v** [SpikeApp/Spike#20]
![img_e2545](https://user-images.githubusercontent.com/16197536/37412760-d9910b82-27a5-11e8-971f-7524a91567ec.JPG)

Two values seem to overlap at the bottom.

**Comment by miguelkennedy** [comment]
Hi, this is not a bug... you simply have 2 thresholds that are too close to each other... there's nothing we can do to avoid the overlap, especially because your chart is going from 2.6 to 23.4 so Spike doesn't have enough space to fit everything...

**Comment by m-a-v** [comment]
You could probably omti the higher values if the font will overlap. Like this the users can at least read one of the values. For me it's OK if it is not fixed.

**Comment by miguelkennedy** [comment]
I'm sorry but it does not grant a fix... it's not up to spike to omit values... this same overlap also happens in Nightscout for a reason ;)
