### ISSUE TITLE
Spike does not work with iOS13.3

### ISSUE THREAD

**Issue by osodebailar** [SpikeApp/Spike#220]
After resigning spike with newest Xcode and sdk , spike will not be installed on iPhone 11pro with iOS13.3 beta

**Comment by Vladimir153** [comment]
А когда будет рабочая версия?

**Comment by igorakaamigo** [comment]
Hi!
The issue is referred to new XCode versions, not the iOS version itself.
 I'm signing the app using an old XCode9, which can be obtained here: https://developer.apple.com/download/more/
Hope this helps.
Regards.

**Comment by m-a-v** [comment]
Spike works with iOS 13.3. If you need more details about installation, join the FB group.
