### ISSUE TITLE
Spike won't install on iPhone

### ISSUE THREAD

**Issue by mploug** [SpikeApp/Spike#230]
Hello,
How come Spike won't install on iPhone?
Getting an error 71.

Thank you in advance.

Kind regards,
Martin

**Comment by yrliko** [comment]
Apple killed the certification.

**Comment by mploug** [comment]
Thank you. What can you install instead?

**Comment by yrliko** [comment]
I am using Dexcom app, more stable,

in our group, I saw those one make iphone crack,
crack means your iphone will not updated in future.
apple also has not to control the certification.

then use spike
https://www.iphonecake.com/app/
other app:
https://share.weiyun.com/5aRLxVz
Water3/越狱苹果可用/spike_3.6.1.ipa



mploug <notifications@github.com>于2020年7月1日 周三下午2:46写道：

**Comment by m-a-v** [comment]
@yrliko I've deleted your post. Please don't post any unofficial links.
