### ISSUE TITLE
Unable to install spike.iphone-ipodtouch.3.6.3-resigned

### ISSUE THREAD

**Issue by HJS64** [SpikeApp/Spike#231]
https://spike-app.com/install-spike-using-xcode/

- Following the instructions for manual install
- Free Apple Developer Account
- Signing for iPhone

Everything works well, but at the end I cannot install the app on my iPhone 7.
Message:
unable to install spike.iphone-ipodtouch.3.6.3-resigned.

Any idea how to fix this?

**Comment by CoreISP** [comment]
Hi Hendrik, a solution to this problem is available in Spike's Facebook group. Suggest you join that. :)

**Comment by HJS64** [comment]
Thank jou, but ….. I hate Facebook.
I think I have no choice right now, so I will have a look.

Thanks for your reply.

Met vriendelijke groet,
Hendrik Jan
