### ISSUE TITLE
Error" Can't find watch extension's mobileprovision file. Please make sure you performed all Xcode steps correctly. Aborting!"

### ISSUE THREAD

**Issue by Steel121** [SpikeApp/Spike#237]
When I run the resigning script I get this error. I DID comment out lines 366 and 423 but still receive this error.

Is there something else that I need to cmment out?

**Comment by m-a-v** [comment]
Not that I know of. Did you follow all the other steps correctly?

**Comment by Steel121** [comment]
I think so but the guide also uses a different version of xcode with a developer account so the screens don't match  1 for 1. I am using a free account.

**Comment by m-a-v** [comment]
The manual on the homepage is no longer up-to-date. I will transfer it to GitHub and update it. In the meantime, it's best to use the instructions in the Facebook group. Thanks for your understanding.

**Comment by Steel121** [comment]
I don't have an active facebook account. Any chance you can paste?

**Comment by m-a-v** [comment]
Sorry, this is not possible. I recommend you to create an account. Even if you need more information and help. Or you wait until I have updated the installation manual which will certainly take some time.

**Comment by Steel121** [comment]
ok thanks for the quick responses

**Comment by prewk** [comment]
@m-a-v Please write a comment in this issue when you've updated <3
