### ISSUE TITLE
Sometimes uploads to Nightscout missing

### ISSUE THREAD

**Issue by JohanDegraeve** [SpikeApp/Spike#24]
It looks as if sometimes uploads to Nightscout fail, although the logs shows the upload was successful.
I think it happens after a reconnect.

Example attached screenshot spike shows no gaps.
![spike](https://user-images.githubusercontent.com/13840461/38723816-8df304c2-3f02-11e8-80d3-28046e54383c.JPG)

Here Nightscout, there's a gap at 09:15. Also in mongolab I don't find this event.
![capture](https://user-images.githubusercontent.com/13840461/38723863-b4a35356-3f02-11e8-9052-09a8087ca76e.JPG)

Here the logs.
The event is created at 09:15:24.610
The upload to NS shows successful at 09:15:25.482

[IssueLog.txt](https://github.com/SpikeApp/Spike/files/1906417/IssueLog.txt)

**Comment by miguelkennedy** [comment]
Thank you... I noticed it too... On my TODO to check what might be wrong... The logs are helpful ;)

**Comment by miguelkennedy** [comment]
Fixed... See https://github.com/SpikeApp/Spike/commit/7f0023e953c961329efc13553b63d8e61d3a6b9d
