### ISSUE TITLE
IOS 14 update

### ISSUE THREAD

**Issue by Millercio** [SpikeApp/Spike#240]
Today the new version of IOS has come out, the 14.
After installing the update on the phone I tried to open Spike but I got an error message, which said:
"The developer must update this App to work with IOS 14"

Does anyone know if there is already a Spike update, and how it has to be installed?

Thank you very much to all

**Comment by liroyvh** [comment]
You simply need to re-sign with latest software (AS/XCode/Impactor) to fix it.

**Comment by simgislab** [comment]
iOS 14.7.1
Cydia Impactor
Current version of the app from 
https://spike-app.com/releases/latest-iphone-impactor-version

If you're having:
![изображение](https://user-images.githubusercontent.com/172806/132393060-0ded27fb-b962-46e1-9bf0-c019ddde7662.png)

Solution: update Cydia Impactor to latest version
