### ISSUE TITLE
Possibility to view >24h

### ISSUE THREAD

**Issue by BaQs** [SpikeApp/Spike#244]
Hello,

Having the need to check which bolus amount I took yesterday, i think having the ability to see 27h ago would be nice.
Do you think that would be possible?

🙏

**Comment by m-a-v** [comment]
On a master it is possible to view historic values. Just open the main menu on the left and open the History function. There are many answers to such questions in the Facebook group.

**Comment by BaQs** [comment]
I'm actually using spike as a follower. Xdrip4ios as a master (cgm is libre2)
