### ISSUE TITLE
Spike does not update

### ISSUE THREAD

**Issue by HelomSilva** [SpikeApp/Spike#248]
Since I installed Spike, it does not follow up values. It stays « frozen » at the time the app was launched.

I am using Miao Miao 3 as transmissor. Any idea how to solve this problem?

iOS 15.2.1
Iphone 12 Pro Max

**Comment by tannygamer007** [comment]
I too am facing Same issue.in iPhone 6 with miao miao 3.How did you push the spike code to iPhone 12 pro Max?? I was unable to push it to iPhone xs Max and iPhone 12.

**Comment by tannygamer007** [comment]
And what spike version are you currently running on iPhone 12 pro Max???you can check it in settings of spike and about section..

**Comment by jawngee** [comment]
Are you using a US Freestyle Libre 2?

**Comment by LiroyvH** [comment]
@tannygamer007 Late reply is late, but who knows - maybe someone has the same questions and finds this. So: install instructions for latest iOS version are only in the Facebook group. However, with a MM3 you can spare yourself the trouble - we don't support that transmitter in Spike. However, we do support it in xDrip4iOS. Note that for FSL2 we only support the EU model; which does not require a transmitter-bridge at all, direct connect.
