### ISSUE TITLE
Spike Update needed for IOS 16.5.1

### ISSUE THREAD

**Issue by Snuffyz2** [SpikeApp/Spike#249]
Spike-iPhone-iPodTouch-Cydia-Impactor.ipa downloaded 12 July 2023 does not run on IOS 16.5.1.  It indicates an update is needed to run on this IOS .
How will I get this?

**Comment by LiroyvH** [comment]
It even runs on iOS 17, so you're probably using instructions other than those provided in the Facebook group. (Which are the only valid ones.)
