### ISSUE TITLE
Error installing and signing on Mac OS X Sequoia - IOS 18

### ISSUE THREAD

**Issue by dpecile** [SpikeApp/Spike#253]
Hi
Apparently the location of the certificates, changed, from 
"${HOME}/Library/MobileDevice/Provisioning Profiles"
to 
"${HOME}/Library/Developer/Xcode/UserData/Provisioning Profiles"

I changed the signing script, but, after succefully signed the IPA, I have the error when try to install on iPhone.

0xe8008016 (The executable was signed with invalid entitlements.)

Any idea ? 
I am using the free account from Apple.

Thanks ins advance.

**Comment by m-a-v** [comment]
As you've mentioned there is a different handling regarding path for Xcode 16. I've created a PR. Feel free to test it with this version. I was only testing it with the paid account and it works flawlessly on my side.

**Comment by m-a-v** [comment]
Fix merged to main. Please test and report back. I will close the issue for now.
