### ISSUE TITLE
Initial calibration problem

### ISSUE THREAD

**Issue by francesc0-cgm** [SpikeApp/Spike#30]
Since new initial single calibration alghoritm was introduced i am having a lot of problem with accuracy in the first hours of sensor life. Seems it starts to over or underestimate bg till a new calibration is inserted. Usually i insert the sensor continuing last session, i wait half an hour so initial noise goes away and i put the measure when bgs are stable (using loop). With new alghoritm bgs seems crazy till i insert a second calibration.

**Comment by JohanDegraeve** [comment]
I propose we wait till we get more feedback from other users.

**Comment by miguelkennedy** [comment]
Agree... I''m not facing any issues myself...

**Comment by m-a-v** [comment]
I didn’t face any problems either (Libre).

**Comment by davidmlb** [comment]
no problems at all, ( libre ang G5), but I use two blood glucose strips to be sure the value I put in the calibration is a real value

**Comment by brookslively** [comment]
I have this same problem. I've gone through 4 or so sensors since I've started and run into the same issue each time. I haven't figured out a good solution yet other than to wait and recalibrate after a bit. I'm using a G5 with an iPhone 6s currently running iOS 11.3.1 and on the latest version of Spike. Always use a 2+ hr soak. An example from my nightscout report is below. Let me know if I can help with testing anything out.

![image](https://user-images.githubusercontent.com/10806975/41802159-b5bdab70-7633-11e8-9f4d-65c5730fa90e.png)

**Comment by brookslively** [comment]
Is there data I could collect when I start a new sensor that could be me/us troubleshoot?

**Comment by francesc0-cgm** [comment]
Imho some sensors have much noise than others. I found that with only calibration they started crazy then calibrating it again it went ok.

**Comment by miguelkennedy** [comment]
When this happens just wait 10-15 minutes and insert a new calibration (overriding the previous one). This tends to fix the issue... It seems to be related to sensor noise...

**Comment by brookslively** [comment]
I just changed my transmitter this evening and ran into the same issue. I was hoping changing the transmitter would help, but this sensor startup calibration issue happens every time for me without fail. I feel like I have to be doing something wrong...

![img_2143](https://user-images.githubusercontent.com/10806975/43178041-3b7c6df4-8f80-11e8-863c-f7465fd6d4eb.PNG)

**Comment by miguelkennedy** [comment]
You added you initial calibration when your BG was going down so that confused the algorithm... when that happens just wait for a new reading an insert a new calibration...

**Comment by miguelkennedy** [comment]
@JohanDegraeve found a fix for this. It will be released Wednesday (Spike version 3.5.2). Closing this issue now as it's 100% fixed. Just download the new update when we release it Wednesday.
