### ISSUE TITLE
Unable to Recognize New Transmitter

### ISSUE THREAD

**Issue by AngieWing** [SpikeApp/Spike#31]
I have a new transmitter. One that we put batteries in, not a factory issued one. I entered the transmitter ID. However, the “refresh” button to search for the transmitter via Bluetooth is not clickable. I did “forget” the old transmitter in my Bluetooth settings.

**Comment by miguelkennedy** [comment]
What transmitter type are you using?

**Comment by AngieWing** [comment]
G5

*ANGELA WING*
*630-725-8939*
*SlackerPancreas.com*
*IG: angela.wing*
angiewing0101@gmail.com
