### ISSUE TITLE
Hammers AppleCar Play

### ISSUE THREAD

**Issue by NerdyEE** [SpikeApp/Spike#33]
If Spike is running and plugged into AppleCar Play on my 2017 Bolt, audio will dump into Apple iPod mode and out of Sirius XM or other audio source....

Dexcom has similar issue but only if opened (top). Previously Dexcom would jump this mode every 5 minutes but would jump back to previous audio source. Spike locks in iPod mode within in seconds of plug in....

**Comment by miguelkennedy** [comment]
Try going to Spike's settings, advanced and enable alternative method #1 when you're in the car... See if it fixes it... After you leave the car be sure to turn off this option, it wastes more battery

**Comment by NerdyEE** [comment]
Thanks Miguel!
I think that cured it as I also had to increase the settings as the collection average was not looking good. Thus why I thought the use of previous data would help you and everyone...

So if I got an iWatch for referee work, would Spike gather data while on soccer pitch and away from iPhone??? Or still data holes....

-J

**Comment by NerdyEE** [comment]
Hi again Miguel,
I left other comments on the other thread about past data...

Just tried iPhone on my car and initial plug in to car does still change mode to iPOD mode. Yes I can jump back to XM but undesired feature to change the CarPlay modes.....

**Comment by miguelkennedy** [comment]
Have you tried enabling alternative method before entering the car?

**Comment by NerdyEE** [comment]
Yes everything was enabled when I plugged in....

-J

**Comment by miguelkennedy** [comment]
Then as a last resort try to keep Spike open and without locking the screen (click the three dots menu on the upper right corner and select no lock"... When Spike is open and the screen doesn't lock Spike will not use iPhone's audio
