### ISSUE TITLE
Blucon Start and Stop

### ISSUE THREAD

**Issue by anapaulalago** [SpikeApp/Spike#36]
I do not have the START and STOP BluCon buttons anymore. Is this an Enhancement? If I get a faulty sensor and start a new one using Abbott’s default reader it will reflect as a START date on Spike?

**Comment by miguelkennedy** [comment]
Correct... No need to start/stop sensors anymore if you're using BluCon... Just place your BluCon on top of the new Libre sensor and Spike will stop the previous in-app sensor and start a new one based on the time/date you activated the new Libre sensor.
