### ISSUE TITLE
Dynamic Chart

### ISSUE THREAD

**Issue by anapaulalago** [SpikeApp/Spike#37]
Dynamic chart sometimes squeezes the pie chart and distribution table on the bottom part of my iPhoneX screen making it both unreadable. Happens on initial setup (or reinstall) when with few data I make a BG calibration that is below previous points.

**Comment by miguelkennedy** [comment]
Hi... Can you provide a screenshot?

**Comment by anapaulalago** [comment]
Issue solved with all updates.

**Comment by miguelkennedy** [comment]
Yes, I did make some fixes... Glad it's working correctly now ;)
