### ISSUE TITLE
some values are jumping 

### ISSUE THREAD

**Issue by davidmlb** [SpikeApp/Spike#44]
I’m looping for a 5 days with freestyle-miao-spike and loop. I’m really happy with the accuracy of the combination. Free are reading values more close to he blood value, are really faster to Dexcom, and I made only the first calibration an the second day to adjust 6-7 points.
 When the blood glucose is raising freestyle says more than real, but doesn’t t mater because as soon the tendency change also free is changing, and when the blood glucose is falling close to 140 mg/dl  freestyle is in a real value. In a low values free is saying the correct value. I have now two sensor in parallel ( dexcom g4 and frestyle). 

The only thing I’m not happy is sometimes some values are changing or jumping to a wrong values for example  82, 84, 86, 71, 88, could be some setting to improve it? 

Thanks
![jump](https://user-images.githubusercontent.com/28386261/40126764-8a3d8340-591d-11e8-86ba-13267b3169b6.jpg)

**Comment by miguelkennedy** [comment]
Sorry, just saw this...

There is no setting to improve this... those glucose jumps are being sent by MiaoMiao to Spike... this normally happens with new sensors that need more time to settle in the body... Normally when sensors have been inserted less than 24-48h ago
