### ISSUE TITLE
Not ble activate any function on the + pull down menu. Attemting to Calibrate but no go.

### ISSUE THREAD

**Issue by lillyholme** [SpikeApp/Spike#47]
Attempting to Calibrate on the spike + pull down menu but no go. When I push calibrate it does not work.

**Comment by miguelkennedy** [comment]
Is the button greyed out?

**Comment by lillyholme** [comment]
Yes all were greyed out,  but suddenly they were functioning okay. This has happened yesterday and today.

**Comment by miguelkennedy** [comment]
When they are greyed out it means you don't have recent readings or no initial calibration inserted

**Comment by lillyholme** [comment]
OK, that make sense. I missed the signal from CGM,  G4 XBridge and in that respect I tried to set the BG by using the calibration function.
