### ISSUE TITLE
Feature Request: Carbs/insulin from Apple Health

### ISSUE THREAD

**Issue by georgebarnett** [SpikeApp/Spike#48]
I use multiple apps on my phone to manage my BGs.

As a result, I often end up entering treatments (carbs/insulin) in the other apps because their calculator functions are very advanced and also their food data is comprehensive.

After I have entered the treatments in these apps, they store the data into apple health and so I would like these to show up in Spike because the user interface is so good!

I would also like to have Spike push these carbs and insulin up to nightscout so my followers can see that I've taken action and not worry.

Thanks for the great App!

**Comment by miguelkennedy** [comment]
Hi!

For now there's no plans on reading carbs and insulin from HK into Spike... Maybe on a future update but it's not a priority at the moment because we are very busy with new features. If we add this feature we will also push this data to Nightscout.
