### ISSUE TITLE
spike-dexcom app. 

### ISSUE THREAD

**Issue by davidmlb** [SpikeApp/Spike#49]
Hi I was working for a long time with loop-g5-spike, loop-miao-spike, and Works fine, now I need to comming back to loop-g5-dexcom app. and I have two diferents loop app. one is a master aon other is a developer versión, both i have with the code changes done to work with a spike, and hapens that in one loop when i push the glucose source is going to spike spite i have not selected spike server, and in the other app is going to dexcom app spite i have selected spike app. doesn'y mater the server you have selected, all times are going to the same app. I have made a hard reset, but the problema persist. 
thanks

**Comment by miguelkennedy** [comment]
Hey David, this doesn't seem to be an issue with Spike... Spike does not send values to Loop, rather Loop requests values from Spike...

Maybe post this issue in Loop's GitHub or Gitter channel, you might find more relevant answers there...
