### ISSUE TITLE
request: Link indicator icon in status bar

### ISSUE THREAD

**Issue by moccon** [SpikeApp/Spike#5]
For new starters it might be unclear if the App is connected. My idea is to implement an Link icon in the status bar which indicates if the App is connected with the Transmitter.
For Blucon par example, the Ambrosia app has a link icon which switches from red to green.

**Comment by miguelkennedy** [comment]
I think you have that in menu -> transmitter... We might do a statusbar icon somewhere in the future but I can't give an ETA as we have essential features to be added first..

**Comment by moccon** [comment]
Ofcourse. I had some Bluetooth drops without noticing, it could be handy to always see if you're connected in the first place.  So far app is much stabler than previous versions. Very happy with it.

**Comment by miguelkennedy** [comment]
Awesome! Thanks for the feedback! ;)

**Comment by moccon** [comment]
Hi Miguel, I still cannot tell if Spike is 'connected' and working by the look at it... Just have to wait and wait, (an icon would be so helpful) but now I found a workaround, just want to let you know!  
if I toggle the Bluetooth icon very short it (sometimes) immediately connects..
