### ISSUE TITLE
127.0.0.1:1979/sgv.json - units_hint returns mmol but value returns mg/dL

### ISSUE THREAD

**Issue by retroneo** [SpikeApp/Spike#50]
127.0.0.1:1979/sgv.json - units_hint returns mmol but value returns mg/dL

Example:

`[{"sgv":167,"direction":"FortyFiveUp","dateString":"2018-06-23T13:18:20.000+0000","date":1529759900449,"sysTime":"2018-06-23T13:18:20.000+0000","units_hint":"mmol","noise":1,"delta":6}]`

**Comment by miguelkennedy** [comment]
Yes... this is the correct behaviour... values are always returned in mg/dL, it's up to the user/client to do the conversion...
