### ISSUE TITLE
Updating Spike

### ISSUE THREAD

**Issue by vilegodsk78** [SpikeApp/Spike#68]
When you try to update the Spike of the Proverm Test Flight, asks for a new code. Is it correct? How to get a new code?

**Comment by miguelkennedy** [comment]
Hi, this should not happen.

Please email support@spike-app.com letting is now your apple id email and I will send you a new invite

**Comment by vilegodsk78** [comment]
Thank you. Everything turned out!

чт, 12 июля 2018, 19:01 Miguel Kennedy <notifications@github.com>:
