### ISSUE TITLE
interpunction , or . 

### ISSUE THREAD

**Issue by moccon** [SpikeApp/Spike#7]
Hi there, i almost entered wrong value with calibrating. 
European (Dutch) values are seperated with , not .   
Thanks again!

**Comment by miguelkennedy** [comment]
Can you elaborate a bit more? You are on mmol, correct? doesn't the keyboard that appear in the calibration popup have a , and a .?

**Comment by moccon** [comment]
mmol yes. Yes the keyboard has it. Doesn't work you can type a 6,5 and it will give you 65!

**Comment by miguelkennedy** [comment]
Fixed! Next Spike update will allow you to input commas (,) in the calibration popup... 

Going to close this issue ;)

**Comment by moccon** [comment]
Top!
