### ISSUE TITLE
Alarm repeater doesn't respect if alarm exists or not

### ISSUE THREAD

**Issue by miguelkennedy** [SpikeApp/Spike#8]
Scenario: User has a high alarm set, the alarm fires and starts repeating every minute. While the alarm is still on "repeat mode" the user goes to the settings and deletes that alarm. Even after the alarm has been deleted, the "repeat mode" still continues to play the deleted alarm.

**Comment by JohanDegraeve** [comment]
I will take that one

Op vr 23 feb. 2018 om 15:41 schreef RooTShell <notifications@github.com>

**Comment by miguelkennedy** [comment]
Don't forget to push changes I've been making to the master first... No features added, just fixes...
